public with sharing class NGCC_Contact_Search_Utility {
        
        public String getFirstNameId(){
            return '&name_firstlea2=';
        }
        public String getLastNameId(){
            return '&name_lastlea2=';
        }
        public String getCompanyId(){
            return '&lea3=';
        }
        public String getAddress1Id(){
            return '&00N30000000gcCs=';
        }
        public String getAddress2Id(){
            return '&00N30000000gcCu=';
        }
        public String getCityId(){
            return '&00N30000000gcCx=';
        }
        public String getStateId(){
            return '&00N30000000gcDJ=';
        }
        public String getCountryId(){
            return '&00N30000000gcCy=';
        }
        public String getZipId(){
            return '&00N30000000gcDN=';
        }
        public String getEmailId(){
            return '&lea11=';
        }
        public String getPhoneId(){
            return '&lea8=';
        }
        public String getSourceId(){
            return '&CF00Nn0000000Glo0=';
        }
        public String getEndCustomerId(){
            return '&CF00N80000004wo4w=';
        }
        public String getMODSId(){
            return '&00Nn0000000Glo7=';
        }
        public String getCampaignId(){
            return '&CF00Nn0000000SzyY';
        }
        public String getCampaingCode(){
            return '&00Nn0000000SzyX=';
        }
        public String getProgramName (){
            return '&00N30000001Wlm5=';
        }
        public String getProgramCode (){
            return '&00N30000000gcDB=';
        }
        public String getSiteId(){
            return '&00Nn0000000P07L=';
        }
}